apiVersion: v1
kind: Namespace
metadata:
  name: acm-policies
  annotations:
    openshift.io/description: "Centralized namespace for all general ACM policies"
    openshift.io/display-name: "ACM Cluster Policies"
