apiVersion: policy.open-cluster-management.io/v1beta1
kind: PolicySet
metadata:
  name: ocp-managed-clusters-policyset
  namespace: acm-policies
spec:
  description: policy set to apply to all OCP managed clusters
  policies:
    - acs-operator-installed
    - cert-manager-operator-installed
