apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: vsphere-cluster-autoscaler-configured
  namespace: acm-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53, NIST-CSF
    policy.open-cluster-management.io/categories: CM Configuration Management, PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration, PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-cluster-autoscaler
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: "autoscaling.openshift.io/v1"
                kind: "ClusterAutoscaler"
                metadata:
                  name: "default"
                spec:
                  podPriorityThreshold: -10 
                  resourceLimits:
                    maxNodesTotal: 24 
                    cores:
                      min: 8 
                      max: 128 
                    memory:
                      min: 4 
                      max: 256 
                    gpus:
                      - type: nvidia.com/gpu 
                        min: 0 
                        max: 16 
                      - type: amd.com/gpu 
                        min: 0 
                        max: 4 
                  scaleDown: 
                    enabled: true 
                    delayAfterAdd: 10m 
                    delayAfterDelete: 5m 
                    delayAfterFailure: 30s 
                    unneededTime: 5m 
                    utilizationThreshold: "0.4"
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-worker-machine-autoscaler
        spec:
          remediationAction: inform
          severity: low
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: "autoscaling.openshift.io/v1beta1"
                kind: "MachineAutoscaler"
                metadata:
                  name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-worker'
                  namespace: "openshift-machine-api"
                spec:
                  minReplicas: 3
                  maxReplicas: 3
                  scaleTargetRef:
                    apiVersion: machine.openshift.io/v1beta1
                    kind: MachineSet
                    name: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-worker'
